env-oauth: oauth-success

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 756905357383-dji0bitgf687ad3sv2agu9dmu17sd2ij.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

jwt:
  header: Authorization
  secret: frontend_reactjs_backend_springboot_cicd_gitAction_aws_proejctName_helloMyTeam_from2022to2023_ing
  token-validity-in-seconds: 86400