env: default

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: local
    include: oauth

  #Swagger set
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
