env: default-success

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:
  thymeleaf:
    prefix: classpath:templates/admin/
    suffix: .html
    cache: false
#  security:
#    user:
#      name: admin
#      password: hellomyteamadmin123
#      roles: ADMIN

  pid:
    file: /home/ec2-user/app/step2/hellomyteam.pid
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #Swagger set
  profiles:
    active: dev
    group:
      local : local,oauth
      dev : dev,oauth
      prod : prod,oauth

# ------- 파일 업로드 시작 ----------
  servlet:
    multipart:
      enabled: true
#      임시 저장경로 - 파일 확장자 체크
      max-request-size: 10MB
      max-file-size: 10MB
# admin setting
#  boot:
#    admin:
#      client:
#        url: http://localhost:8081 #admin server url
#        instance:
#          name: HelloMyTeam Admin #admin UI 에서 보여질 이름 설정

# aws 파일 업로드 설정 및 오류 제거
cloud:
  aws:
    s3:
      bucket: hellomyteam-fileupload-v1
    credentials:
      access-key: AKIARX6D63VSYNN3ZJU6
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

# ec2 환경이 아닌 local 환경에서 발생하는 aws 오류 제거
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error