server:
  port: 8080

spring:
  profiles:
    include: oauth
    default: local # 기본 환경을 local로

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/hellomyteam
    username: sa
    password:

#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://hellomyteam-dev-db.cj1my6byvuun.ap-northeast-2.rds.amazonaws.com:3306/hellomyteam_dev_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: ckdgus988
#    password: tyzm4060!

  jpa:
    hibernate:
      ddl-auto: create
      # 개발 초기 단계 : create / update
      # 테스트 서버 : update / validate
      # 운영 서버 : validate / none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

