env-oauth: oauth-success

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${env.CLIENT_ID}
            client-secret: ${env.CLIENT_SECRET}
            scope: ${env.SCOPE}

jwt:
  header: ${env.JWT_HEADER}
  secret: ${env.JWT_SECRET}
  token-validity-in-seconds: ${env.JWT_TOKEN_SECONDS}