env: default

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #Swagger set
  profiles:
    group:
      "local" : "local, oauth"
      "dev" : "dev, oauth"
      "prod" : "prod, oauth"

---
#로컬
spring:
  config:
    activate:
      on-profile: "local"

---
#개발
spring:
  config:
    activate:
      on-profile: dev

---
#운영
spring:
  config:
    activate:
      on-profile: prod
