## main.yml의 최상단입니다.
#
env:
  S3_BUCKET_NAME: hellomyteam-github-action-s3-bucket
  PROJECT_NAME: hellomyteam
  CODE_DEPLOY_APP_NAME: hellomyteam-webservice
  CODE_DEPLOY_GROUP_NAME: hellomyteam-webservice-back

name: deploy-staging

on:
  push:
    branches: [ release ]

jobs:
  deploy:      # job 이름
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Github-Actions     # Github Actions 사용을 위한 체크아웃
        uses: actions/checkout@v2

      - name: Install Java 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Permission for Gradle
        run: chmod +x ./gradlew

      - name: Start Build with Gradle
        run: ./gradlew clean build

      - name: Setting for AWS          # AWS 권한셋팅
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3             # 빌드파일 S3 업로드
        run: aws deploy push --region ap-northeast-2 ./$PROJECT_NAME.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$PROJECT_NAME.zip  #(14)

      - name: Start Deploy with CodeDeploy      # CodeDeploy 실행
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name $CODE_DEPLOY_GROUP_NAME --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$PROJECT_NAME.zip    #(16)
